---
# This is the command you need:
# after this has been run, make sure to install apt-get install python-apt
# MAKE SURE TO DO THIS BIT FIRST
# ansible-playbook -c paramiko -i hosts setup.yml --ask-pass --sudo
# change hosts: line to reflect which host acts on
- hosts: all
  sudo: yes
  user: pi
  vars: 
    ansible_ssh_user: pi
    ansible_ssh_pass: raspberry
    #ansible_ssh_port: 5986
    #ansible_connection: winrm  
 
  roles:
    - initial_setup
    - common
